### ISSUE TITLE
REST Sample

### ISSUE THREAD

**Issue by magallardo** [MoerkerkeLander/camera-feed-object-detector-tf-serve#3]
You mentioned you used REST to access the models running in docker.  Could you please provide the sample REST calls?

**Comment by LanderMoerkerke** [comment]
Since I no longer maintain this repository, I won't run through the setup steps again. I could however refer you these links those are quite extensive and well written out. Adapting to my codebase should be fairly simple:

- [RESTful API  |  TFX  |  TensorFlow](https://www.tensorflow.org/tfx/serving/api_rest)
- [Train and serve a TensorFlow model with TensorFlow Serving  |  TFX](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple)
